# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Sukahideng
email: sukahideng@openthinklabs.com
description: > # this means to ignore newlines until "baseurl:"
  Dari Abu Hurairah radhiyallahu ‘anhu, ia berkata bahwa Rasulullah shallallahu ‘alaihi wa sallam bersabda,<br/>
    إِذَا مَاتَ الْإِنْسَانُ انْقَطَعَ عَمَلُهُ إِلَّا مِنْ ثَلَاثَةٍ مِنْ صَدَقَةٍ جَارِيَةٍ وَعِلْمٍ يُنْتَفَعُ بِهِ وَوَلَدٍ صَالِحٍ يَدْعُو لَهُ
  <br/>"Jika seseorang meninggal dunia, maka terputuslah amalannya kecuali tiga perkara (yaitu): sedekah jariyah, ilmu yang dimanfaatkan, atau do’a anak yang sholeh" (HR. Muslim no. 1631)
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://sukahideng.openthinklabs.com" # the base hostname & protocol for your site
twitter_username: sukahideng
#instagram_username:  sukahideng
#facebook_username: Graha Aquaponik

# Build settings
markdown: kramdown
